### ISSUE TITLE
设置 ip 失败

### ISSUE THREAD

**Issue by kaizhang-shanxi** [laincloud/lain-box#4]
软件版本为

+ Vagrant 1.9.1
+ VirtualBox 5.1.12

时，设置虚拟机 IP 会失败。报错为 `/sbin/ifdown 'eth1'` 失败。

**Comment by kaizhang-shanxi** [comment]
这个问题产生的原因是 centos 用 `ifup`/`ifdown` 管理网络，而 vagrant 会尝试用 `nmcli` 设置网络，两者不兼容。将

```
config.vm.network "private_network", ip: cfg["ip"]
```

改为

```
config.vm.network "private_network", ip: cfg["ip"], auto_config: false
```

可解决此问题。

**Comment by fossilet** [comment]
Vagrant 1.9.4, VirtualBox 5.1.22，有同样的问题，上述方法可解决。
